name: Flowdock Poster
on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
  post-it:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    name: Posts the PR to a flowdock flow
    steps:
    - name: Filter PR Author
      uses: TechSmith/action-flowdock-usermap@1.0.0
      id: filter
    - name: Post PR to flow
      uses: TechSmith/flowdock-post-action@1.1.0
      with:
        organization: 'techsmith'
        flow: ${{ steps.filter.outputs.flow }}
        flowdock_api_token: ${{ secrets.FLOWDOCK_API_KEY }}
